travis:
  secure:
    BINSTAR_TOKEN: qnyWp8xp9yYpWYAGjp7buBxGeGm2KJ6p8gjUesZy3LJhD2DpExwHBu8PSSh3nD2dCRyF2/oOqJWcyYVc7eU3lBnLV3A62JtStWXVBIiBAERTPDeuqt1jC+srwFtJnX460HKpDQsM8ZG46EuvT9QzEY9vjcOAFo70cAwxC13BH+lstJ5oHRNohZLs6hjqkv3KvVhaji9Zdvh8DMS/izATzRHBguydN9u0Fg+amxIPFm/e5oze8zQ+HKaCTbjX173vrk6AWlLC+cU4IGYlssFPMN5K3vdZtlQCrkwQaLhlaQnZuPJlS4uKzr9IILjuqJ8Pi8pgffjDpam3MLMt7NjfMsBXYbkRRkDH+s8rUxIxoKNZx2DWWxW2zfxYC65Ba6Ni8D1GhT0DvQ+OhhvU9ZVTDyBTM+ildnrzbLNWaxTVgupMlmolPC59bH7+OVHcgWWUHozPV8KvpjKaM+lTIl5hRQG1HIcJdixhXHibQfAnHzuBOmhj0hMFl/wJZ2SVhPhVczq/A+5Iua8QPOB1MUaNDa8EzuAVYndZ0w1T9KDFYAsqECMdtTVSttvW1HO9koYNg1TAEGu1VyXKBVqXRRSVYvQt/BGc8Y2r5wIYC/C3Lxk/p+AXWKftKO82+Ovn9WWVFm47f5ybqblbf9vzYcuWg4miKS8nYdmdud8Io43gHmg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
